### ISSUE TITLE
I updated to the latest and get this error on an infinite loop

### ISSUE THREAD

**Issue by CodisRedding** [cspotcode/mockery-next#16]
```
1) Route - Link Player "before each" hook for "should return bad request when provider id is unknown":
     RangeError: Maximum call stack size exceeded
      at disabled (node_modules/debug/debug.js:65:20)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:741:3)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref/lib/ref.js:742:11)
...
```

**Comment by cspotcode** [comment]
At first glance, it looks like the `ref` module doesn't like being loaded more than once.  That's out of the scope of `mockery`.  You'll have to somehow restructure your tests to avoid loading `ref` multiple times.
